{
	"version": 1527094205,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/creditos-sheet0.png",
		"images/splash-sheet0.png",
		"images/menu-sheet0.png",
		"images/play-sheet0.png",
		"images/newgame.png",
		"images/ibaralho-sheet0.png",
		"images/icard-sheet0.png",
		"images/icard-sheet1.png",
		"images/sensorcartas-sheet0.png",
		"images/bmenu-sheet0.png",
		"images/som-sheet0.png",
		"images/som-sheet1.png",
		"images/nota-sheet0.png",
		"images/nota-sheet1.png",
		"images/icoin-sheet0.png",
		"media/iwan gabovitch - dark ambience loop.ogg",
		"media/draw.m4a",
		"media/draw.ogg",
		"media/passturn.m4a",
		"media/passturn.ogg",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/untap.m4a",
		"media/untap.ogg",
		"media/path to lake land.ogg",
		"media/explosion1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}